// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaIFp97f89q-ySe3hEF0Mbq2L54MXDABA',
    appId: '1:287481209317:web:5b628e2db5096d54dc4f0c',
    messagingSenderId: '287481209317',
    projectId: 'my-daily-cds',
    authDomain: 'my-daily-cds.firebaseapp.com',
    storageBucket: 'my-daily-cds.appspot.com',
    measurementId: 'G-KHYQWH97ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe613WNbksCrVCwuojw7xyrzAZE8JMtHo',
    appId: '1:287481209317:android:55dac0a008475ac4dc4f0c',
    messagingSenderId: '287481209317',
    projectId: 'my-daily-cds',
    storageBucket: 'my-daily-cds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQdiEpgExM30nBQ_86dPcj_0meSndeGis',
    appId: '1:287481209317:ios:14565d225161b910dc4f0c',
    messagingSenderId: '287481209317',
    projectId: 'my-daily-cds',
    storageBucket: 'my-daily-cds.appspot.com',
    androidClientId: '287481209317-c1dvdh23ejmgu8i0ok241lvg2gqipvr1.apps.googleusercontent.com',
    iosClientId: '287481209317-ohvqu2h62h5ljvbt5cg60ogulqvl3ko9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyCdPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQdiEpgExM30nBQ_86dPcj_0meSndeGis',
    appId: '1:287481209317:ios:14565d225161b910dc4f0c',
    messagingSenderId: '287481209317',
    projectId: 'my-daily-cds',
    storageBucket: 'my-daily-cds.appspot.com',
    androidClientId: '287481209317-c1dvdh23ejmgu8i0ok241lvg2gqipvr1.apps.googleusercontent.com',
    iosClientId: '287481209317-ohvqu2h62h5ljvbt5cg60ogulqvl3ko9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyCdPlayer',
  );
}
